game-console-backend-mysql:
    #build: ./mysql
    image: jtleon/mysql57:bsw
    privileged: true
    restart: always
    ports:
        - "29674:3306"
    volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/my.cnf:/etc/mysql/my.cnf
        - ./mysql/logs:/var/log/mysql
        - /etc/localtime:/etc/localtime:ro
    environment:
        - MYSQL_ROOT_PASSWORD=Mys9l!7259

game-console-backend-redis:
    build: ./redis
    privileged: true
    restart: always
    ports:
        - "32747:6379"
    volumes:
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        - ./redis/data:/data

game-console-backend-fpm:
    #build: ./php
    image: jtleon/php74:bsw
    privileged: true
    restart: always
    volumes:
        - ../:/web/app
        - ../../file:/web/file
        - ./php/php.ini:/usr/local/etc/php/php.ini
        - ./php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.
        - ./php/fpm.conf:/usr/local/etc/php-fpm.d/www.conf
        - /etc/localtime:/etc/localtime:ro
    extra_hosts:
        - "host:${GODDESS2}"
    links:
        - game-console-backend-mysql:mysql
        - game-console-backend-redis:redis

game-console-backend-nginx:
    image: nginx:latest
    privileged: true
    restart: always
    ports:
        - "26448:80"
        - "26811:443"
    volumes:
        - ../:/web/app
        - ../../file:/web/file
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/logs:/var/log/nginx
        - ./nginx/cert/app.crt:/etc/nginx/app.crt
        - ./nginx/cert/app.key:/etc/nginx/app.key
    links:
        - game-console-backend-fpm:fpm
